/* Imágenes de las tarjetas: «baraja|anverso» → media/tarjetas/<nombre>.webp.
   Si una tarjeta no está aquí, se queda con su icono. Las imágenes no se precachean: se cargan al mostrarlas.
   GENERADO por tools/generar_tarjetas_img.py desde recursos/tarjetas_prompts/*.json: no editar a mano. */
const TARJETAS_IMG = {
 "kant|A priori": "a_priori",
 "platon|Mundo inteligible": "mundo_inteligible",
 "ipc-falacias|Hombre de paja": "hombre_de_paja",
 "existencialismo|Mala fe": "mala_fe",
 "siglo21|Modernidad líquida": "modernidad_liquida",
 "fil-posverdad|Cámara de eco": "camara_de_eco",
 "historicidad|Historicidad": "historicidad",
 "historicidad|Universalidad": "universalidad",
 "historicidad|Canon": "canon",
 "historicidad|Transmisión": "transmision",
 "metodos|Argumento": "argumento",
 "fil-metodo|Argumento": "argumento",
 "ipc-conceptos|Argumento": "argumento",
 "metodos|Falacia": "falacia",
 "metodos|Principio de caridad": "principio_de_caridad",
 "metodos|Método filosófico": "metodo_filosofico",
 "metodos|Género filosófico": "genero_filosofico",
 "mito|¿Quién explica el mundo?": "quien_explica_el_mundo",
 "mito|¿Cómo se transmite?": "como_se_transmite",
 "mito|¿Se puede discutir?": "se_puede_discutir",
 "mito|physis": "physis",
 "mito|arché": "arche",
 "mito|Necesidad (ananké)": "ananke",
 "aporias|Antropomorfismo": "antropomorfismo",
 "aporias|Regreso infinito de causas": "regreso_infinito",
 "aporias|Lo uno y lo múltiple": "uno_y_multiple",
 "aporias|Lo general y lo singular": "general_y_singular",
 "aporias|Naturaleza y convención": "naturaleza_y_convencion",
 "sofistas|physis / nomos": "naturaleza_y_convencion",
 "aporias|El cambio y la permanencia": "cambio_y_permanencia",
 "aporias|El movimiento (Zenón)": "movimiento_zenon",
 "aporias|Purificación del alma": "purificacion_del_alma",
 "aporias|Sentidos y razón": "sentidos_y_razon",
 "aporias|La identidad personal": "identidad_personal",
 "fil-identidad|Identidad personal": "identidad_personal",
 "aporias|Las preguntas como motor": "preguntas_como_motor",
 "sofistas|La Ilustración griega": "ilustracion_griega",
 "sofistas|Los sofistas": "los_sofistas",
 "sofistas|Protágoras": "protagoras",
 "sofistas|Gorgias": "gorgias",
 "sofistas|Hipias": "hipias",
 "sofistas|Sócrates": "socrates",
 "sofistas|Ironía y mayéutica": "ironia_y_mayeutica",
 "antropologia|Mayéutica": "ironia_y_mayeutica",
 "sofistas|Aspasia de Mileto": "aspasia",
 "sofistas|Cobrar por enseñar": "cobrar_por_ensenar",
 "sofistas|A quién enseñan": "a_quien_ensenan",
 "sofistas|Qué enseñan": "que_ensenan",
 "sofistas|Cómo viven": "como_viven",
 "sofistas|Intelectualismo moral": "intelectualismo_moral",
 "antropologia|Intelectualismo moral": "intelectualismo_moral",
 "etica|Intelectualismo moral": "intelectualismo_moral",
 "sofistas|Docta ignorancia": "docta_ignorancia",
 "sofistas|Jenofonte": "jenofonte",
 "platon|Idea (Forma)": "idea_forma",
 "platon|Mundo sensible": "mundo_sensible",
 "platon|Doxa": "doxa",
 "platon|Episteme": "episteme",
 "platon|Dialéctica": "dialectica",
 "platon|Reminiscencia (anamnesis)": "reminiscencia",
 "antropologia|Reminiscencia": "reminiscencia",
 "platon|Paideia": "paideia",
 "platon|Dualismo ontológico": "dualismo_ontologico",
 "platon|Dualismo antropológico": "dualismo_antropologico",
 "antropologia|Dualismo": "dualismo_antropologico",
 "metafisica|Dualismo": "dualismo_antropologico",
 "fil-mente|Dualismo": "dualismo_antropologico",
 "platon|Rey filósofo": "rey_filosofo",
 "politica|Rey filósofo": "rey_filosofo",
 "platon|Demiurgo": "demiurgo",
 "platon|Del caos al cosmos": "del_caos_al_cosmos",
 "platon|Alma del mundo": "alma_del_mundo",
 "platon|Visión teleológica": "vision_teleologica",
 "platon|Un mundo matemático": "mundo_matematico",
 "platon|Cosmogonía: un relato verosímil": "cosmogonia_relato",
 "platon|Aristóteles frente a Platón": "aristoteles_frente_a_platon",
 "antropologia|Psique": "psique",
 "antropologia|Giro antropológico": "giro_antropologico",
 "antropologia|Hilemorfismo": "hilemorfismo",
 "antropologia|Metempsicosis": "metempsicosis",
 "antropologia|Acto y potencia": "acto_y_potencia",
 "antropologia|Las cuatro causas": "cuatro_causas",
 "antropologia|Motor inmóvil": "motor_inmovil",
 "etica|Ética": "etica",
 "etica|Areté": "arete",
 "etica|Eudaimonía": "eudaimonia",
 "etica|Virtudes dianoéticas": "virtudes_dianoeticas",
 "etica|Virtudes éticas": "virtudes_eticas",
 "etica|Término medio": "termino_medio",
 "etica|Prudencia": "prudencia",
 "politica|Polis": "polis",
 "politica|Utopía": "utopia",
 "politica|Zoon politikón": "zoon_politikon",
 "politica|Monarquía": "monarquia",
 "politica|Aristocracia": "aristocracia",
 "politica|República": "republica",
 "politica|Tiranía": "tirania",
 "politica|Demagogia": "demagogia",
 "politica|Ostracismo": "ostracismo",
 "politica|Clase media": "clase_media",
 "helenismo|Helenismo": "helenismo",
 "helenismo|Autarquía": "autarquia",
 "helenismo|Logos": "logos_estoico",
 "helenismo|Apatía": "apatia",
 "helenismo|Ataraxia": "ataraxia",
 "helenismo|Aponía": "aponia",
 "helenismo|Tetrafármaco": "tetrafarmaco",
 "fil-helenismo|El tetrafármaco": "tetrafarmaco",
 "helenismo|Epojé": "epoje",
 "helenismo|Cosmopolitismo": "cosmopolitismo",
 "helenismo|Lathe biosas": "lathe_biosas",
 "helenismo|Koiné": "koine",
 "medieval|Patrística": "patristica",
 "medieval|Escolástica": "escolastica",
 "medieval|Universales": "universales",
 "medieval|Nominalismo": "nominalismo",
 "medieval|Microcosmos": "microcosmos",
 "medieval|Macrocosmos": "macrocosmos",
 "medieval|Neoplatonismo": "neoplatonismo",
 "medieval|Conversión": "conversion",
 "medieval|Interioridad": "interioridad",
 "feRazon|Creación": "creacion",
 "feRazon|Emanación": "emanacion",
 "feRazon|Iluminación": "iluminacion",
 "feRazon|Cinco vías": "cinco_vias",
 "feRazon|Navaja de Ockham": "navaja_de_ockham",
 "feRazon|Verdad sobrenatural": "verdad_sobrenatural",
 "feRazon|Verdad natural": "verdad_natural",
 "feRazon|Ley natural": "ley_natural",
 "feRazon|Trivium y quadrivium": "trivium_quadrivium",
 "modernidad|Humanismo": "humanismo",
 "modernidad|Antropocentrismo": "antropocentrismo",
 "modernidad|Heliocentrismo": "heliocentrismo",
 "modernidad|Mecanicismo": "mecanicismo",
 "modernidad|Positivismo": "positivismo",
 "modernidad|Secularización": "secularizacion",
 "modernidad|Dignitas hominis": "dignitas_hominis",
 "modernidad|Virtù": "virtu",
 "metafisica|Sustancia": "sustancia",
 "metafisica|Res cogitans": "res_cogitans",
 "metafisica|Res extensa": "res_extensa",
 "metafisica|Materialismo": "materialismo",
 "metafisica|Determinismo": "determinismo",
 "metafisica|Hombre-máquina": "hombre_maquina",
 "metafisica|Mónadas": "monadas",
 "metafisica|Ocasionalismo": "ocasionalismo",
 "contrato|Contrato social": "contrato_social",
 "fil-politica|El contrato social": "contrato_social",
 "contrato|Estado de naturaleza": "estado_de_naturaleza",
 "contrato|Leviatán": "leviatan",
 "fil-politica|Hobbes y el Leviatán": "leviatan",
 "contrato|Derechos naturales": "derechos_naturales",
 "ilustracion|Derechos naturales": "derechos_naturales",
 "contrato|Voluntad general": "voluntad_general",
 "contrato|Estado de derecho": "estado_de_derecho",
 "contrato|Coerción": "coercion",
 "utilitarismo|Liberalismo": "liberalismo",
 "utilitarismo|Utilitarismo": "utilitarismo",
 "utilitarismo|Principio de la mayor felicidad": "mayor_felicidad",
 "eticaDeber|Principio de utilidad": "mayor_felicidad",
 "utilitarismo|Mano invisible": "mano_invisible",
 "utilitarismo|Propiedad privada": "propiedad_privada",
 "utilitarismo|Darwinismo social": "darwinismo_social",
 "utilitarismo|Cooperación": "cooperacion"
};
