/* Imágenes de las tarjetas: «baraja|anverso» → media/tarjetas/<nombre>.webp.
   Si una tarjeta no está aquí, se queda con su icono. Las imágenes no se precachean: se cargan al mostrarlas.
   GENERADO por tools/generar_tarjetas_img.py desde recursos/tarjetas_prompts/*.json: no editar a mano. */
const TARJETAS_IMG = {
 "kant|A priori": "a_priori",
 "platon|Mundo inteligible": "mundo_inteligible",
 "platon|Mundu adigarria": "mundo_inteligible",
 "ipc-falacias|Hombre de paja": "hombre_de_paja",
 "ipc-falacias|Lastozko gizona": "hombre_de_paja",
 "ipc-falacias|稻草人": "hombre_de_paja",
 "existencialismo|Mala fe": "mala_fe",
 "existencialismo|Fede txarra": "mala_fe",
 "beauvoir|Mala fe": "mala_fe",
 "beauvoir|Fede txarra": "mala_fe",
 "siglo21|Modernidad líquida": "modernidad_liquida",
 "siglo21|Modernitate likidoa": "modernidad_liquida",
 "fil-posverdad|Cámara de eco": "camara_de_eco",
 "fil-posverdad|Oihartzun-ganbera": "camara_de_eco",
 "historicidad|Historicidad": "historicidad",
 "historicidad|Historikotasuna": "historicidad",
 "historicidad|Universalidad": "universalidad",
 "historicidad|Unibertsaltasuna": "universalidad",
 "historicidad|Canon": "canon",
 "historicidad|Kanona": "canon",
 "historicidad|Transmisión": "transmision",
 "historicidad|Transmisioa": "transmision",
 "metodos|Argumento": "argumento",
 "metodos|Argudioa": "argumento",
 "metodos|论证": "argumento",
 "fil-metodo|Argumento": "argumento",
 "fil-metodo|Argudioa": "argumento",
 "fil-metodo|论证": "argumento",
 "ipc-conceptos|Argumento": "argumento",
 "ipc-conceptos|Argudioa": "argumento",
 "ipc-conceptos|论证": "argumento",
 "metodos|Falacia": "falacia",
 "metodos|Faltsukeria": "falacia",
 "metodos|谬误": "falacia",
 "fil-metodo|Falacia": "falacia",
 "fil-metodo|Faltsukeria": "falacia",
 "fil-metodo|谬误": "falacia",
 "metodos|Principio de caridad": "principio_de_caridad",
 "metodos|Karitate-printzipioa": "principio_de_caridad",
 "metodos|善意原则": "principio_de_caridad",
 "ipc-conceptos|Principio de caridad": "principio_de_caridad",
 "ipc-conceptos|Karitate-printzipioa": "principio_de_caridad",
 "ipc-conceptos|善意原则": "principio_de_caridad",
 "metodos|Método filosófico": "metodo_filosofico",
 "metodos|Metodo filosofikoa": "metodo_filosofico",
 "metodos|Género filosófico": "genero_filosofico",
 "metodos|Genero filosofikoa": "genero_filosofico",
 "mito|¿Quién explica el mundo?": "quien_explica_el_mundo",
 "mito|Nork azaltzen du mundua?": "quien_explica_el_mundo",
 "fil-que-es|Del mito al logos": "quien_explica_el_mundo",
 "fil-que-es|Mitotik logosera": "quien_explica_el_mundo",
 "fil-presocraticos|Del mito al logos": "quien_explica_el_mundo",
 "fil-presocraticos|Mitotik logosera": "quien_explica_el_mundo",
 "mito|¿Cómo se transmite?": "como_se_transmite",
 "mito|Nola transmititzen da?": "como_se_transmite",
 "mito|¿Se puede discutir?": "se_puede_discutir",
 "mito|Eztabaida al daiteke?": "se_puede_discutir",
 "fil-que-es|Saber racional y crítico": "se_puede_discutir",
 "fil-que-es|Jakintza arrazional eta kritikoa": "se_puede_discutir",
 "fil-caracteristicas|Frente al mito": "se_puede_discutir",
 "fil-caracteristicas|Mitoaren aurrean": "se_puede_discutir",
 "mito|physis": "physis",
 "fil-que-es|Physis": "physis",
 "fil-presocraticos|Los «físicos»": "physis",
 "fil-presocraticos|«Fisikoak»": "physis",
 "presocraticos|Fragmento B 30": "physis",
 "presocraticos|B 30 zatia": "physis",
 "mito|arché": "arche",
 "mito|arkhe": "arche",
 "fil-que-es|Arché": "arche",
 "fil-que-es|Arkhe": "arche",
 "fil-presocraticos|El arché": "arche",
 "fil-presocraticos|Arkhea": "arche",
 "mito|Necesidad (ananké)": "ananke",
 "mito|Beharrezkotasuna (ananke)": "ananke",
 "aporias|Antropomorfismo": "antropomorfismo",
 "aporias|Antropomorfismoa": "antropomorfismo",
 "fil-presocraticos|Jenófanes de Colofón": "antropomorfismo",
 "fil-presocraticos|Xenofanes Kolofongoa": "antropomorfismo",
 "presocraticos|Jenófanes": "antropomorfismo",
 "presocraticos|Xenofanes": "antropomorfismo",
 "aporias|Regreso infinito de causas": "regreso_infinito",
 "aporias|Kausen erregresio infinitua": "regreso_infinito",
 "aporias|Lo uno y lo múltiple": "uno_y_multiple",
 "aporias|Bata eta anitza": "uno_y_multiple",
 "aporias|Lo general y lo singular": "general_y_singular",
 "aporias|Orokorra eta singularra": "general_y_singular",
 "aporias|Naturaleza y convención": "naturaleza_y_convencion",
 "aporias|Natura eta konbentzioa": "naturaleza_y_convencion",
 "sofistas|physis / nomos": "naturaleza_y_convencion",
 "aporias|El cambio y la permanencia": "cambio_y_permanencia",
 "aporias|Aldaketa eta iraupena": "cambio_y_permanencia",
 "fil-presocraticos|Heráclito de Éfeso": "cambio_y_permanencia",
 "fil-presocraticos|Heraklito Efesokoa": "cambio_y_permanencia",
 "presocraticos|Heráclito": "cambio_y_permanencia",
 "presocraticos|Heraklito": "cambio_y_permanencia",
 "presocraticos|Heráclito frente a Parménides": "cambio_y_permanencia",
 "presocraticos|Heraklito Parmenidesen aurrean": "cambio_y_permanencia",
 "presocraticos|«Nada permanece, todo fluye» (panta rei)": "cambio_y_permanencia",
 "presocraticos|«Ezerk ez du irauten, dena isurtzen da» (panta rei)": "cambio_y_permanencia",
 "aporias|El movimiento (Zenón)": "movimiento_zenon",
 "aporias|Mugimendua (Zenon)": "movimiento_zenon",
 "presocraticos|Zenón de Elea": "movimiento_zenon",
 "presocraticos|Zenon Eleakoa": "movimiento_zenon",
 "aporias|Purificación del alma": "purificacion_del_alma",
 "aporias|Arimaren purifikazioa": "purificacion_del_alma",
 "fil-mente|Alma (Platón)": "purificacion_del_alma",
 "fil-mente|Arima (Platon)": "purificacion_del_alma",
 "fil-concepciones|Platón": "purificacion_del_alma",
 "fil-concepciones|Platon": "purificacion_del_alma",
 "fil-concepciones|柏拉图": "purificacion_del_alma",
 "aporias|Sentidos y razón": "sentidos_y_razon",
 "aporias|Zentzumenak eta arrazoia": "sentidos_y_razon",
 "aporias|La identidad personal": "identidad_personal",
 "aporias|Identitate pertsonala": "identidad_personal",
 "fil-identidad|Identidad personal": "identidad_personal",
 "fil-identidad|Nortasun pertsonala": "identidad_personal",
 "fil-ser-humano|Identidad personal": "identidad_personal",
 "fil-ser-humano|Nortasun pertsonala": "identidad_personal",
 "fil-identidad|Barco de Teseo": "identidad_personal",
 "fil-identidad|Teseoren ontzia": "identidad_personal",
 "aporias|Las preguntas como motor": "preguntas_como_motor",
 "aporias|Galderak motor gisa": "preguntas_como_motor",
 "sofistas|La Ilustración griega": "ilustracion_griega",
 "sofistas|Ilustrazio greziarra": "ilustracion_griega",
 "sofistas|Los sofistas": "los_sofistas",
 "sofistas|Sofistak": "los_sofistas",
 "sofistas|Protágoras": "protagoras",
 "sofistas|Protagoras": "protagoras",
 "sofistas|Gorgias": "gorgias",
 "sofistas|Hipias": "hipias",
 "sofistas|Sócrates": "socrates",
 "sofistas|Sokrates": "socrates",
 "sofistas|苏格拉底": "socrates",
 "sofistas|Ironía y mayéutica": "ironia_y_mayeutica",
 "sofistas|Ironia eta maieutika": "ironia_y_mayeutica",
 "antropologia|Mayéutica": "ironia_y_mayeutica",
 "antropologia|Maieutika": "ironia_y_mayeutica",
 "fil-metodo|Mayéutica (Sócrates)": "ironia_y_mayeutica",
 "fil-metodo|Maiotika (Sokrates)": "ironia_y_mayeutica",
 "sofistas|Aspasia de Mileto": "aspasia",
 "sofistas|Aspasia Miletokoa": "aspasia",
 "sofistas|Cobrar por enseñar": "cobrar_por_ensenar",
 "sofistas|Irakasteagatik kobratzea": "cobrar_por_ensenar",
 "sofistas|A quién enseñan": "a_quien_ensenan",
 "sofistas|Nori irakasten dioten": "a_quien_ensenan",
 "sofistas|Qué enseñan": "que_ensenan",
 "sofistas|Zer irakasten duten": "que_ensenan",
 "sofistas|Cómo viven": "como_viven",
 "sofistas|Nola bizi diren": "como_viven",
 "sofistas|Intelectualismo moral": "intelectualismo_moral",
 "sofistas|Intelektualismo morala": "intelectualismo_moral",
 "antropologia|Intelectualismo moral": "intelectualismo_moral",
 "antropologia|Intelektualismo morala": "intelectualismo_moral",
 "etica|Intelectualismo moral": "intelectualismo_moral",
 "etica|Intelektualismo morala": "intelectualismo_moral",
 "sofistas|Docta ignorancia": "docta_ignorancia",
 "sofistas|Ezjakintasun jakintsua": "docta_ignorancia",
 "fil-metodo|Ironía socrática": "docta_ignorancia",
 "fil-metodo|Ironia sokratikoa": "docta_ignorancia",
 "sofistas|Jenofonte": "jenofonte",
 "sofistas|Xenofonte": "jenofonte",
 "platon|Idea (Forma)": "idea_forma",
 "platon|Ideia (Forma)": "idea_forma",
 "platon|Mundo sensible": "mundo_sensible",
 "platon|Mundu sentikorra": "mundo_sensible",
 "platon|Doxa": "doxa",
 "platon|Episteme": "episteme",
 "fil-saberes|Episteme y doxa": "episteme",
 "fil-saberes|Episteme eta doxa": "episteme",
 "platon|Dialéctica": "dialectica",
 "platon|Dialektika": "dialectica",
 "platon|Reminiscencia (anamnesis)": "reminiscencia",
 "platon|Oroitzapena (anamnesis)": "reminiscencia",
 "antropologia|Reminiscencia": "reminiscencia",
 "antropologia|Oroitzapena": "reminiscencia",
 "platon|Paideia": "paideia",
 "platon|Dualismo ontológico": "dualismo_ontologico",
 "platon|Dualismo ontologikoa": "dualismo_ontologico",
 "platon|Dualismo antropológico": "dualismo_antropologico",
 "platon|Dualismo antropologikoa": "dualismo_antropologico",
 "antropologia|Dualismo": "dualismo_antropologico",
 "antropologia|Dualismoa": "dualismo_antropologico",
 "metafisica|Dualismo": "dualismo_antropologico",
 "metafisica|Dualismoa": "dualismo_antropologico",
 "fil-mente|Dualismo": "dualismo_antropologico",
 "fil-mente|Dualismoa": "dualismo_antropologico",
 "fil-ser-humano|Dualismo": "dualismo_antropologico",
 "fil-ser-humano|Dualismoa": "dualismo_antropologico",
 "platon|Rey filósofo": "rey_filosofo",
 "platon|Errege filosofoa": "rey_filosofo",
 "politica|Rey filósofo": "rey_filosofo",
 "politica|Errege filosofoa": "rey_filosofo",
 "platon|Demiurgo": "demiurgo",
 "platon|Demiurgoa": "demiurgo",
 "platon|Del caos al cosmos": "del_caos_al_cosmos",
 "platon|Kaosetik kosmosera": "del_caos_al_cosmos",
 "platon|Alma del mundo": "alma_del_mundo",
 "platon|Munduaren arima": "alma_del_mundo",
 "platon|Visión teleológica": "vision_teleologica",
 "platon|Ikuspegi teleologikoa": "vision_teleologica",
 "platon|Un mundo matemático": "mundo_matematico",
 "platon|Mundu matematiko bat": "mundo_matematico",
 "platon|Cosmogonía: un relato verosímil": "cosmogonia_relato",
 "platon|Kosmogonia: egiantzeko kontakizuna": "cosmogonia_relato",
 "platon|Aristóteles frente a Platón": "aristoteles_frente_a_platon",
 "platon|Aristoteles Platonen aurrean": "aristoteles_frente_a_platon",
 "antropologia|Psique": "psique",
 "antropologia|Psikea": "psique",
 "antropologia|Giro antropológico": "giro_antropologico",
 "antropologia|Bira antropologikoa": "giro_antropologico",
 "antropologia|Hilemorfismo": "hilemorfismo",
 "antropologia|Hilemorfismoa": "hilemorfismo",
 "antropologia|Metempsicosis": "metempsicosis",
 "antropologia|Metenpsikosia": "metempsicosis",
 "antropologia|Acto y potencia": "acto_y_potencia",
 "antropologia|Aktua eta potentzia": "acto_y_potencia",
 "antropologia|Las cuatro causas": "cuatro_causas",
 "antropologia|Lau kausak": "cuatro_causas",
 "antropologia|Motor inmóvil": "motor_inmovil",
 "antropologia|Motor geldia": "motor_inmovil",
 "etica|Ética": "etica",
 "etica|Etika": "etica",
 "fil-ramas|Ética": "etica",
 "fil-ramas|Etika": "etica",
 "etica|Areté": "arete",
 "etica|Arete": "arete",
 "etica|Eudaimonía": "eudaimonia",
 "etica|Eudaimonia": "eudaimonia",
 "fil-etica|Eudaimonismo": "eudaimonia",
 "fil-etica|Eudaimonismoa": "eudaimonia",
 "etica|Virtudes dianoéticas": "virtudes_dianoeticas",
 "etica|Bertute dianoetikoak": "virtudes_dianoeticas",
 "etica|Virtudes éticas": "virtudes_eticas",
 "etica|Bertute etikoak": "virtudes_eticas",
 "etica|Término medio": "termino_medio",
 "etica|Termino erdikoa": "termino_medio",
 "fil-etica|Virtud": "termino_medio",
 "fil-etica|Bertutea": "termino_medio",
 "etica|Prudencia": "prudencia",
 "etica|Zuhurtzia": "prudencia",
 "politica|Polis": "polis",
 "politica|Polis-a": "polis",
 "politica|Utopía": "utopia",
 "politica|Utopia": "utopia",
 "politica|Zoon politikón": "zoon_politikon",
 "politica|Zoon politikon": "zoon_politikon",
 "fil-concepciones|Aristóteles": "zoon_politikon",
 "fil-concepciones|Aristoteles": "zoon_politikon",
 "fil-politica|El animal político": "zoon_politikon",
 "fil-politica|Animalia politikoa": "zoon_politikon",
 "politica|Monarquía": "monarquia",
 "politica|Monarkia": "monarquia",
 "politica|Aristocracia": "aristocracia",
 "politica|Aristokrazia": "aristocracia",
 "politica|República": "republica",
 "politica|Errepublika": "republica",
 "politica|Tiranía": "tirania",
 "politica|Tirania": "tirania",
 "politica|Demagogia": "demagogia",
 "politica|Ostracismo": "ostracismo",
 "politica|Ostrakismoa": "ostracismo",
 "politica|Clase media": "clase_media",
 "politica|Klase ertaina": "clase_media",
 "helenismo|Helenismo": "helenismo",
 "helenismo|Helenismoa": "helenismo",
 "helenismo|Autarquía": "autarquia",
 "helenismo|Autarkia": "autarquia",
 "fil-helenismo|Cínicos": "autarquia",
 "fil-helenismo|Zinikoak": "autarquia",
 "helenismo|Logos": "logos_estoico",
 "helenismo|Logosa": "logos_estoico",
 "presocraticos|«Según una medida»": "logos_estoico",
 "presocraticos|«Neurriaren arabera»": "logos_estoico",
 "helenismo|Apatía": "apatia",
 "helenismo|Apatia": "apatia",
 "fil-helenismo|Estoicos": "apatia",
 "fil-helenismo|Estoikoak": "apatia",
 "helenismo|Ataraxia": "ataraxia",
 "fil-helenismo|Ataraxia": "ataraxia",
 "helenismo|Aponía": "aponia",
 "helenismo|Aponia": "aponia",
 "fil-helenismo|Epicúreos": "aponia",
 "fil-helenismo|Epikureoak": "aponia",
 "helenismo|Tetrafármaco": "tetrafarmaco",
 "helenismo|Tetrafarmakoa": "tetrafarmaco",
 "fil-helenismo|El tetrafármaco": "tetrafarmaco",
 "fil-helenismo|Tetrafarmakoa": "tetrafarmaco",
 "helenismo|Epojé": "epoje",
 "helenismo|Epokhe": "epoje",
 "fil-helenismo|Escépticos": "epoje",
 "fil-helenismo|Eszeptikoak": "epoje",
 "helenismo|Cosmopolitismo": "cosmopolitismo",
 "helenismo|Kosmopolitismoa": "cosmopolitismo",
 "fil-helenismo|Cosmopolitismo": "cosmopolitismo",
 "fil-helenismo|Kosmopolitismoa": "cosmopolitismo",
 "helenismo|Lathe biosas": "lathe_biosas",
 "helenismo|Koiné": "koine",
 "helenismo|Koine": "koine",
 "medieval|Patrística": "patristica",
 "medieval|Patristika": "patristica",
 "medieval|Escolástica": "escolastica",
 "medieval|Eskolastika": "escolastica",
 "medieval|Universales": "universales",
 "medieval|Unibertsalak": "universales",
 "medieval|Nominalismo": "nominalismo",
 "medieval|Nominalismoa": "nominalismo",
 "medieval|Microcosmos": "microcosmos",
 "medieval|Mikrokosmosa": "microcosmos",
 "medieval|Macrocosmos": "macrocosmos",
 "medieval|Makrokosmosa": "macrocosmos",
 "medieval|Neoplatonismo": "neoplatonismo",
 "medieval|Neoplatonismoa": "neoplatonismo",
 "medieval|Conversión": "conversion",
 "medieval|Konbertsioa": "conversion",
 "medieval|Interioridad": "interioridad",
 "medieval|Barrentasuna": "interioridad",
 "presocraticos|«Me investigué a mí mismo»": "interioridad",
 "presocraticos|«Neure burua ikertu nuen»": "interioridad",
 "feRazon|Creación": "creacion",
 "feRazon|Kreazioa": "creacion",
 "feRazon|Emanación": "emanacion",
 "feRazon|Emanazioa": "emanacion",
 "feRazon|Iluminación": "iluminacion",
 "feRazon|Iluminazioa": "iluminacion",
 "feRazon|Cinco vías": "cinco_vias",
 "feRazon|Bost bideak": "cinco_vias",
 "feRazon|Navaja de Ockham": "navaja_de_ockham",
 "feRazon|Ockhamen labana": "navaja_de_ockham",
 "feRazon|Verdad sobrenatural": "verdad_sobrenatural",
 "feRazon|Egia naturaz gaindikoa": "verdad_sobrenatural",
 "feRazon|Verdad natural": "verdad_natural",
 "feRazon|Egia naturala": "verdad_natural",
 "feRazon|Ley natural": "ley_natural",
 "feRazon|Lege naturala": "ley_natural",
 "feRazon|Trivium y quadrivium": "trivium_quadrivium",
 "feRazon|Trivium eta quadrivium": "trivium_quadrivium",
 "modernidad|Humanismo": "humanismo",
 "modernidad|Humanismoa": "humanismo",
 "modernidad|Antropocentrismo": "antropocentrismo",
 "modernidad|Antropozentrismoa": "antropocentrismo",
 "modernidad|Heliocentrismo": "heliocentrismo",
 "modernidad|Heliozentrismoa": "heliocentrismo",
 "modernidad|Mecanicismo": "mecanicismo",
 "modernidad|Mekanizismoa": "mecanicismo",
 "modernidad|Positivismo": "positivismo",
 "modernidad|Positibismoa": "positivismo",
 "modernidad|Secularización": "secularizacion",
 "modernidad|Sekularizazioa": "secularizacion",
 "modernidad|Dignitas hominis": "dignitas_hominis",
 "modernidad|Virtù": "virtu",
 "metafisica|Sustancia": "sustancia",
 "metafisica|Substantzia": "sustancia",
 "metafisica|Res cogitans": "res_cogitans",
 "fil-mente|Res cogitans / res extensa": "res_cogitans",
 "fil-concepciones|Descartes": "res_cogitans",
 "metafisica|Res extensa": "res_extensa",
 "metafisica|Materialismo": "materialismo",
 "metafisica|Materialismoa": "materialismo",
 "fil-ser-humano|Monismo materialista": "materialismo",
 "fil-mente|Monismo materialista": "materialismo",
 "metafisica|Determinismo": "determinismo",
 "metafisica|Determinismoa": "determinismo",
 "kant|Determinismo": "determinismo",
 "kant|Determinismoa": "determinismo",
 "metafisica|Hombre-máquina": "hombre_maquina",
 "metafisica|Gizaki-makina": "hombre_maquina",
 "metafisica|Mónadas": "monadas",
 "metafisica|Monadak": "monadas",
 "metafisica|Ocasionalismo": "ocasionalismo",
 "metafisica|Okasionalismoa": "ocasionalismo",
 "contrato|Contrato social": "contrato_social",
 "contrato|Kontratu soziala": "contrato_social",
 "fil-politica|El contrato social": "contrato_social",
 "fil-politica|Gizarte-kontratua": "contrato_social",
 "contrato|Estado de naturaleza": "estado_de_naturaleza",
 "contrato|Naturazko egoera": "estado_de_naturaleza",
 "contrato|Leviatán": "leviatan",
 "contrato|Leviatan": "leviatan",
 "fil-politica|Hobbes y el Leviatán": "leviatan",
 "fil-politica|Hobbes eta Leviatana": "leviatan",
 "contrato|Derechos naturales": "derechos_naturales",
 "contrato|Eskubide naturalak": "derechos_naturales",
 "ilustracion|Derechos naturales": "derechos_naturales",
 "ilustracion|Eskubide naturalak": "derechos_naturales",
 "fil-politica|Locke y el Estado liberal": "derechos_naturales",
 "fil-politica|Locke eta Estatu liberala": "derechos_naturales",
 "contrato|Voluntad general": "voluntad_general",
 "contrato|Borondate orokorra": "voluntad_general",
 "fil-politica|Rousseau y la voluntad general": "voluntad_general",
 "fil-politica|Rousseau eta borondate orokorra": "voluntad_general",
 "contrato|Estado de derecho": "estado_de_derecho",
 "contrato|Zuzenbide-estatua": "estado_de_derecho",
 "fil-politica|Estado de derecho": "estado_de_derecho",
 "fil-politica|Zuzenbide-estatua": "estado_de_derecho",
 "contrato|Coerción": "coercion",
 "contrato|Hertsapena": "coercion",
 "utilitarismo|Liberalismo": "liberalismo",
 "utilitarismo|Liberalismoa": "liberalismo",
 "utilitarismo|Utilitarismo": "utilitarismo",
 "utilitarismo|Utilitarismoa": "utilitarismo",
 "utilitarismo|功利主义": "utilitarismo",
 "fil-etica|Utilitarismo": "utilitarismo",
 "fil-etica|Utilitarismoa": "utilitarismo",
 "fil-etica|功利主义": "utilitarismo",
 "utilitarismo|Principio de la mayor felicidad": "mayor_felicidad",
 "utilitarismo|Zoriontasun handienaren printzipioa": "mayor_felicidad",
 "eticaDeber|Principio de utilidad": "mayor_felicidad",
 "eticaDeber|Baliagarritasunaren printzipioa": "mayor_felicidad",
 "utilitarismo|Mano invisible": "mano_invisible",
 "utilitarismo|Esku ikusezina": "mano_invisible",
 "utilitarismo|Propiedad privada": "propiedad_privada",
 "utilitarismo|Jabetza pribatua": "propiedad_privada",
 "utilitarismo|Darwinismo social": "darwinismo_social",
 "utilitarismo|Sozialdarwinismoa": "darwinismo_social",
 "utilitarismo|Cooperación": "cooperacion",
 "utilitarismo|Lankidetza": "cooperacion",
 "utilitarismo|合作": "cooperacion",
 "kant|A posteriori": "a_posteriori",
 "kant|Formas a priori": "formas_a_priori",
 "kant|A priori formak": "formas_a_priori",
 "kant|Juicio analítico": "juicio_analitico",
 "kant|Judizio analitikoa": "juicio_analitico",
 "kant|Juicio sintético": "juicio_sintetico",
 "kant|Judizio sintetikoa": "juicio_sintetico",
 "kant|Juicio sintético a priori": "juicio_sintetico_a_priori",
 "kant|Judizio sintetiko a priori": "juicio_sintetico_a_priori",
 "kant|Empírico": "empirico",
 "kant|Enpirikoa": "empirico",
 "kant|Racionalismo": "racionalismo",
 "kant|Arrazionalismoa": "racionalismo",
 "fil-conocer|Racionalismo": "racionalismo",
 "fil-conocer|Arrazionalismoa": "racionalismo",
 "kant|Empirismo": "empirismo",
 "kant|Enpirismoa": "empirismo",
 "fil-conocer|Empirismo": "empirismo",
 "fil-conocer|Enpirismoa": "empirismo",
 "fil-conocer|Tabula rasa": "empirismo",
 "kant|Experiencia": "experiencia_kant",
 "kant|Esperientzia": "experiencia_kant",
 "kant|Condiciones de la experiencia": "condiciones_experiencia",
 "kant|Esperientziaren baldintzak": "condiciones_experiencia",
 "kant|Límites del conocimiento": "limites_conocimiento",
 "kant|Ezagutzaren mugak": "limites_conocimiento",
 "kant|Sensibilidad": "sensibilidad",
 "kant|Sentimena": "sensibilidad",
 "kant|Intuición": "intuicion",
 "kant|Intuizioa": "intuicion",
 "kant|Espacio": "espacio",
 "kant|Espazioa": "espacio",
 "kant|Tiempo": "tiempo",
 "kant|Denbora": "tiempo",
 "kant|Entendimiento": "entendimiento",
 "kant|Adimena": "entendimiento",
 "kant|Categoría": "categoria",
 "kant|Kategoria": "categoria",
 "kant|Tabla de categorías": "tabla_de_categorias",
 "kant|Kategorien taula": "tabla_de_categorias",
 "kant|Causalidad": "causalidad",
 "kant|Kausalitatea": "causalidad",
 "kant|Necesidad": "necesidad",
 "kant|Beharrezkotasuna": "necesidad",
 "kant|需要": "necesidad",
 "kant|Esquema": "esquema",
 "kant|Eskema": "esquema",
 "kant|模式": "esquema",
 "kant|Imaginación trascendental": "imaginacion_trascendental",
 "kant|Irudimen transzendentala": "imaginacion_trascendental",
 "kant|Función del concepto": "funcion_del_concepto",
 "kant|Kontzeptuaren funtzioa": "funcion_del_concepto",
 "kant|Síntesis": "sintesis",
 "kant|Sintesia": "sintesis",
 "kant|Unidad sintética": "unidad_sintetica",
 "kant|Batasun sintetikoa": "unidad_sintetica",
 "kant|Apercepción trascendental": "apercepcion",
 "kant|Aperzepzio transzendentala": "apercepcion",
 "kant|Sujeto trascendental": "apercepcion",
 "kant|Subjektu transzendentala": "apercepcion",
 "kant|Deducción trascendental": "deduccion_trascendental",
 "kant|Dedukzio transzendentala": "deduccion_trascendental",
 "kant|Universalidad": "universalidad_kant",
 "kant|Unibertsaltasuna": "universalidad_kant",
 "kant|Razón": "razon",
 "kant|Arrazoia": "razon",
 "kant|理由": "razon",
 "kant|Idea trascendental": "idea_trascendental",
 "kant|Ideia transzendentala": "idea_trascendental",
 "kant|Tipos de ideas": "tipos_de_ideas",
 "kant|Ideia motak": "tipos_de_ideas",
 "kant|Alma": "alma_kant",
 "kant|Arima": "alma_kant",
 "kant|Mundo": "mundo_kant",
 "kant|Mundua": "mundo_kant",
 "kant|Dios": "dios_kant",
 "kant|Jainkoa": "dios_kant",
 "kant|Ideal trascendental": "ideal_trascendental",
 "kant|Ideal transzendentala": "ideal_trascendental",
 "kant|Ilusión trascendental": "ilusion_trascendental",
 "kant|Ilusio transzendentala": "ilusion_trascendental",
 "kant|Antinomias": "antinomias",
 "kant|Antinomiak": "antinomias",
 "kant|Paralogismos": "paralogismos",
 "kant|Paralogismoak": "paralogismos",
 "kant|Criticismo": "criticismo",
 "kant|Kritizismoa": "criticismo",
 "fil-conocer|Criticismo (Kant)": "criticismo",
 "fil-conocer|Kritizismoa (Kant)": "criticismo",
 "fil-verdad|Criticismo (Kant)": "criticismo",
 "fil-verdad|Kritizismoa (Kant)": "criticismo",
 "kant|Revolución copernicana": "revolucion_copernicana",
 "kant|Iraultza kopernikarra": "revolucion_copernicana",
 "kant|Idealismo trascendental": "idealismo_trascendental",
 "kant|Idealismo transzendentala": "idealismo_trascendental",
 "kant|Trascendental": "trascendental",
 "kant|Transzendentala": "trascendental",
 "kant|Fenómeno": "fenomeno",
 "kant|Fenomenoa": "fenomeno",
 "kant|Noúmeno": "noumeno",
 "kant|Noumenoa": "noumeno",
 "kant|¿Cómo distingue Kant el fenómeno y el noúmeno?": "noumeno",
 "kant|Nola bereizten ditu Kantek fenomenoa eta noumenoa?": "noumeno",
 "kant|¿Qué límite pone el noúmeno a la metafísica tradicional?": "noumeno",
 "kant|Zer muga jartzen dio noumenoak metafisika tradizionalari?": "noumeno",
 "kant|¿Qué papel tiene el noúmeno en la filosofía de Kant?": "noumeno",
 "kant|Zer zeregin du noumenoak Kanten filosofian?": "noumeno",
 "kant|¿Qué se puede argumentar contra el noúmeno?": "noumeno",
 "kant|Zer argudia daiteke noumenoaren aurka?": "noumeno",
 "kant|Descartes busca un conocimiento cierto de la sustancia. Kant, en cambio…": "noumeno",
 "kant|Descartesek substantziaren ezagutza ziurra bilatzen du. Kantek, aldiz…": "noumeno",
 "kant|¿Qué consecuencia tuvo el noúmeno en la metafísica?": "noumeno",
 "kant|Zer ondorio izan zuen noumenoak metafisikan?": "noumeno",
 "kant|¿Qué visión quiere evitar la teoría del noúmeno?": "noumeno",
 "kant|Zer ikuspegi saihestu nahi du noumenoaren teoriak?": "noumeno",
 "kant|Metafísica racionalista": "metafisica_racionalista",
 "kant|Metafisika arrazionalista": "metafisica_racionalista",
 "kant|Metafísica como ciencia": "metafisica_como_ciencia",
 "kant|Metafisika zientzia gisa": "metafisica_como_ciencia",
 "kant|Naturaleza": "naturaleza_kant",
 "kant|Natura": "naturaleza_kant",
 "kant|Ley": "ley_kant",
 "kant|Legea": "ley_kant",
 "kant|Libertad": "libertad_kant",
 "kant|Askatasuna": "libertad_kant",
 "kant|Moral": "moral_kant",
 "kant|Morala": "moral_kant",
 "kant|Ilustración": "ilustracion",
 "kant|Ilustrazioa": "ilustracion",
 "ilustracion|Ilustración": "ilustracion",
 "ilustracion|Ilustrazioa": "ilustracion",
 "kant|Ideas innatas": "ideas_innatas",
 "kant|Jaiotzetiko ideiak": "ideas_innatas",
 "fil-conocer|Ideas innatas": "ideas_innatas",
 "fil-conocer|Jaiotzetiko ideiak": "ideas_innatas",
 "ilustracion|Sapere aude": "sapere_aude",
 "fil-caracteristicas|Autónoma": "sapere_aude",
 "fil-caracteristicas|Autonomoa": "sapere_aude",
 "ipc-conceptos|Autonomía": "sapere_aude",
 "ipc-conceptos|Autonomia": "sapere_aude",
 "ipc-conceptos|自主": "sapere_aude",
 "ilustracion|Deísmo": "deismo",
 "ilustracion|Deismoa": "deismo",
 "ilustracion|Ciudadano": "ciudadano",
 "ilustracion|Hiritarra": "ciudadano",
 "ilustracion|Dogmatismo": "dogmatismo",
 "ilustracion|Dogmatismoa": "dogmatismo",
 "ilustracion|教条主义": "dogmatismo",
 "fil-verdad|Dogmatismo": "dogmatismo",
 "fil-verdad|Dogmatismoa": "dogmatismo",
 "fil-verdad|教条主义": "dogmatismo",
 "eticaDeber|Ética deontológica": "etica_deontologica",
 "eticaDeber|Etika deontologikoa": "etica_deontologica",
 "fil-etica|Deontología": "etica_deontologica",
 "fil-etica|Deontologia": "etica_deontologica",
 "eticaDeber|Ética teleológica": "etica_teleologica",
 "eticaDeber|Etika teleologikoa": "etica_teleologica",
 "fil-etica|Éticas materiales": "etica_teleologica",
 "fil-etica|Etika materialak": "etica_teleologica",
 "eticaDeber|Cálculo hedónico": "calculo_hedonico",
 "eticaDeber|Kalkulu hedonikoa": "calculo_hedonico",
 "eticaDeber|Imperativo categórico": "imperativo_categorico",
 "eticaDeber|Inperatibo kategorikoa": "imperativo_categorico",
 "eticaDeber|Ética formal": "etica_formal",
 "eticaDeber|Etika formala": "etica_formal",
 "fil-etica|Éticas formales": "etica_formal",
 "fil-etica|Etika formalak": "etica_formal",
 "eticaDeber|Buena voluntad": "buena_voluntad",
 "eticaDeber|Borondate ona": "buena_voluntad",
 "sospecha|Ideología": "ideologia",
 "sospecha|Ideologia": "ideologia",
 "sospecha|Alienación": "alienacion",
 "sospecha|Alienazioa": "alienacion",
 "sospecha|Plusvalía": "plusvalia",
 "sospecha|Plusbalioa": "plusvalia",
 "sospecha|Nihilismo": "nihilismo",
 "sospecha|Nihilismoa": "nihilismo",
 "fil-identidad|Nihilismo": "nihilismo",
 "fil-identidad|Nihilismoa": "nihilismo",
 "sospecha|Superhombre": "superhombre",
 "sospecha|Gaingizakia": "superhombre",
 "fil-concepciones|Nietzsche": "superhombre",
 "sospecha|Voluntad de poder": "voluntad_de_poder",
 "sospecha|Botere-nahia": "voluntad_de_poder",
 "sospecha|Inconsciente": "inconsciente",
 "sospecha|Inkontzientea": "inconsciente",
 "sospecha|Ello / Yo / Superyó": "ello_yo_superyo",
 "sospecha|Hura / Nia / Gain-nia": "ello_yo_superyo",
 "capitalismo|Materialismo histórico": "materialismo_historico",
 "capitalismo|Materialismo historikoa": "materialismo_historico",
 "capitalismo|Razón instrumental": "razon_instrumental",
 "capitalismo|Arrazoi instrumentala": "razon_instrumental",
 "capitalismo|Industria cultural": "industria_cultural",
 "capitalismo|Industria kulturala": "industria_cultural",
 "capitalismo|Ingeniería fragmentaria": "ingenieria_fragmentaria",
 "capitalismo|Ingeniaritza zatikatua": "ingenieria_fragmentaria",
 "capitalismo|Acción comunicativa": "accion_comunicativa",
 "capitalismo|Ekintza komunikatiboa": "accion_comunicativa",
 "posmodernidad|Razón dialógica": "accion_comunicativa",
 "posmodernidad|Arrazoi dialogikoa": "accion_comunicativa",
 "capitalismo|Velo de ignorancia": "velo_de_ignorancia",
 "capitalismo|Ezjakintasunaren estalkia": "velo_de_ignorancia",
 "fil-politica|La justicia (Rawls)": "velo_de_ignorancia",
 "fil-politica|Justizia (Rawls)": "velo_de_ignorancia",
 "capitalismo|Maximin": "maximin",
 "posmodernidad|Genealogía": "genealogia",
 "posmodernidad|Genealogia": "genealogia",
 "posmodernidad|Perspectivismo": "perspectivismo",
 "posmodernidad|Perspektibismoa": "perspectivismo",
 "posmodernidad|Metarrelato": "metarrelato",
 "posmodernidad|Metakontakizuna": "metarrelato",
 "posmodernidad|Deconstrucción": "deconstruccion",
 "posmodernidad|Dekonstrukzioa": "deconstruccion",
 "posmodernidad|Muerte del sujeto": "muerte_del_sujeto",
 "posmodernidad|Subjektuaren heriotza": "muerte_del_sujeto",
 "posmodernidad|Pensamiento débil": "pensamiento_debil",
 "posmodernidad|Pentsamendu ahula": "pensamiento_debil",
 "posmodernidad|Hiperrealidad": "hiperrealidad",
 "posmodernidad|Hiperrealitatea": "hiperrealidad",
 "analitica|Giro lingüístico": "giro_linguistico",
 "analitica|Hizkuntzaren bira": "giro_linguistico",
 "analitica|Atomismo lógico": "atomismo_logico",
 "analitica|Atomismo logikoa": "atomismo_logico",
 "analitica|Neopositivismo": "neopositivismo",
 "analitica|Neopositibismoa": "neopositivismo",
 "analitica|Teoría pictórica": "teoria_pictorica",
 "analitica|Teoria piktorikoa": "teoria_pictorica",
 "analitica|Tautología": "tautologia",
 "analitica|Tautologia": "tautologia",
 "fil-logica|Tautología": "tautologia",
 "fil-logica|Tautologia": "tautologia",
 "analitica|Juegos de lenguaje": "juegos_de_lenguaje",
 "analitica|Hizkuntza-jokoak": "juegos_de_lenguaje",
 "analitica|Terapia lingüística": "terapia_linguistica",
 "analitica|Terapia linguistikoa": "terapia_linguistica",
 "existencialismo|Existencia precede a la esencia": "existencia_precede_esencia",
 "existencialismo|Existentzia esentziaren aurretik dator": "existencia_precede_esencia",
 "fil-concepciones|Sartre (existencialismo)": "existencia_precede_esencia",
 "fil-concepciones|Sartre (existentzialismoa)": "existencia_precede_esencia",
 "existencialismo|Dasein": "dasein",
 "existencialismo|Ser-para-la-muerte": "ser_para_la_muerte",
 "existencialismo|Heriotzarako-izatea": "ser_para_la_muerte",
 "existencialismo|Razón vital": "razon_vital",
 "existencialismo|Bizi-arrazoia": "razon_vital",
 "existencialismo|Circunstancia": "circunstancia",
 "existencialismo|Zirkunstantzia": "circunstancia",
 "existencialismo|Razón poética": "razon_poetica",
 "existencialismo|Arrazoi poetikoa": "razon_poetica",
 "existencialismo|Agonía": "agonia",
 "existencialismo|Agonia": "agonia",
 "beauvoir|Segundo sexo": "segundo_sexo",
 "beauvoir|Bigarren sexua": "segundo_sexo",
 "beauvoir|Lo otro (alteridad)": "alteridad",
 "beauvoir|Bestea (alteritatea)": "alteridad",
 "beauvoir|Inmanencia": "inmanencia",
 "beauvoir|Immanentzia": "inmanencia",
 "beauvoir|Trascendencia": "trascendencia",
 "beauvoir|Transzendentzia": "trascendencia",
 "fil-concepciones|Beauvoir": "trascendencia",
 "beauvoir|Reciprocidad": "reciprocidad",
 "beauvoir|Elkarrekikotasuna": "reciprocidad",
 "beauvoir|Segunda ola": "segunda_ola",
 "beauvoir|Bigarren olatua": "segunda_ola",
 "siglo21|Capitalismo del desastre": "capitalismo_del_desastre",
 "siglo21|Hondamendiaren kapitalismoa": "capitalismo_del_desastre",
 "siglo21|Fabricación del consentimiento": "fabricacion_consentimiento",
 "siglo21|Adostasunaren fabrikazioa": "fabricacion_consentimiento",
 "siglo21|Sociedad del rendimiento": "sociedad_del_rendimiento",
 "siglo21|Errendimenduaren gizartea": "sociedad_del_rendimiento",
 "siglo21|Performance": "performance_genero",
 "siglo21|Performancea": "performance_genero",
 "siglo21|Era farmacopornográfica": "era_farmacopornografica",
 "siglo21|Aro farmakopornografikoa": "era_farmacopornografica",
 "siglo21|Enfoque de las capacidades": "enfoque_capacidades",
 "siglo21|Gaitasunen ikuspegia": "enfoque_capacidades",
 "siglo21|Ecofeminismo": "ecofeminismo",
 "siglo21|Ekofeminismoa": "ecofeminismo",
 "fil-que-es|El asombro": "asombro",
 "fil-que-es|Harridura": "asombro",
 "fil-que-es|Filosofía": "filosofia",
 "fil-que-es|Filosofia": "filosofia",
 "fil-saberes|Filosofía": "filosofia",
 "fil-saberes|Filosofia": "filosofia",
 "fil-que-es|Pregunta radical": "radical",
 "fil-que-es|Galdera erradikala": "radical",
 "fil-caracteristicas|Radical": "radical",
 "fil-caracteristicas|Erradikala": "radical",
 "fil-que-es|Actitud filosófica": "actitud_filosofica",
 "fil-que-es|Jarrera filosofikoa": "actitud_filosofica",
 "fil-caracteristicas|Actitud filosófica": "actitud_filosofica",
 "fil-caracteristicas|Jarrera filosofikoa": "actitud_filosofica",
 "fil-que-es|Filosofía y ciencia": "filosofia_y_ciencia",
 "fil-que-es|Filosofia eta zientzia": "filosofia_y_ciencia",
 "fil-saberes|Filosofía y ciencia": "filosofia_y_ciencia",
 "fil-saberes|Filosofia eta zientzia": "filosofia_y_ciencia",
 "fil-que-es|Filosofía y religión": "filosofia_y_religion",
 "fil-que-es|Filosofia eta erlijioa": "filosofia_y_religion",
 "fil-ramas|Metafísica (ontología)": "metafisica_rama",
 "fil-ramas|Metafisika (ontologia)": "metafisica_rama",
 "fil-ramas|Epistemología (gnoseología)": "epistemologia",
 "fil-ramas|Epistemologia (gnoseologia)": "epistemologia",
 "fil-ramas|Filosofía política": "filosofia_politica",
 "fil-ramas|Filosofia politikoa": "filosofia_politica",
 "fil-ramas|Estética": "estetica",
 "fil-ramas|Estetika": "estetica",
 "fil-ramas|Lógica": "logica_rama",
 "fil-ramas|Logika": "logica_rama",
 "fil-ramas|Antropología filosófica": "antropologia_filosofica",
 "fil-ramas|Antropologia filosofikoa": "antropologia_filosofica",
 "fil-ser-humano|Naturaleza": "naturaleza_humana",
 "fil-ser-humano|Natura": "naturaleza_humana",
 "fil-ser-humano|Cultura": "cultura",
 "fil-ser-humano|Kultura": "cultura",
 "fil-ser-humano|文化": "cultura",
 "fil-ser-humano|Evolución": "evolucion",
 "fil-ser-humano|Eboluzioa": "evolucion",
 "fil-concepciones|Naturalismo evolutivo": "evolucion",
 "fil-concepciones|Naturalismo ebolutiboa": "evolucion",
 "fil-ser-humano|Antepasado común": "antepasado_comun",
 "fil-ser-humano|Arbaso komuna": "antepasado_comun",
 "fil-ser-humano|Hominización": "hominizacion",
 "fil-ser-humano|Hominizazioa": "hominizacion",
 "fil-ser-humano|Naturaleza y cultura": "naturaleza_y_cultura",
 "fil-ser-humano|Natura eta kultura": "naturaleza_y_cultura",
 "fil-ser-humano|Etnocentrismo": "etnocentrismo",
 "fil-ser-humano|Etnzentrismoa": "etnocentrismo",
 "fil-ser-humano|Relativismo cultural": "relativismo_cultural",
 "fil-ser-humano|Erlatibismo kulturala": "relativismo_cultural",
 "fil-conocer|Verdad como correspondencia": "verdad_correspondencia",
 "fil-conocer|Egia korrespondentzia gisa": "verdad_correspondencia",
 "fil-verdad|Verdad como correspondencia": "verdad_correspondencia",
 "fil-verdad|Egia korrespondentzia gisa": "verdad_correspondencia",
 "fil-conocer|Verdad como coherencia": "verdad_coherencia",
 "fil-conocer|Egia koherentzia gisa": "verdad_coherencia",
 "fil-verdad|Verdad como coherencia": "verdad_coherencia",
 "fil-verdad|Egia koherentzia gisa": "verdad_coherencia",
 "fil-conocer|Posverdad": "posverdad",
 "fil-conocer|Postegia": "posverdad",
 "fil-conocer|后真相": "posverdad",
 "fil-posverdad|Posverdad": "posverdad",
 "fil-posverdad|Postegia": "posverdad",
 "fil-posverdad|后真相": "posverdad",
 "fil-conocer|Bulo (fake news)": "bulo",
 "fil-conocer|Gezurra (fake news)": "bulo",
 "fil-conocer|谣言（fake news）": "bulo",
 "fil-posverdad|Bulo (fake news)": "bulo",
 "fil-posverdad|Gezurra (fake news)": "bulo",
 "fil-posverdad|谣言（fake news）": "bulo",
 "fil-conocer|Ciencia": "ciencia",
 "fil-conocer|Zientzia": "ciencia",
 "fil-ciencia|Ciencia": "ciencia",
 "fil-ciencia|Zientzia": "ciencia",
 "fil-saberes|Ciencia": "ciencia",
 "fil-saberes|Zientzia": "ciencia",
 "fil-conocer|Hipótesis": "hipotesis",
 "fil-conocer|Hipotesia": "hipotesis",
 "fil-ciencia|Hipótesis": "hipotesis",
 "fil-ciencia|Hipotesia": "hipotesis",
 "fil-conocer|Falsación (Popper)": "falsacion",
 "fil-conocer|Faltsazioa (Popper)": "falsacion",
 "fil-ciencia|Falsación (Popper)": "falsacion",
 "fil-ciencia|Faltsazioa (Popper)": "falsacion",
 "fil-caracteristicas|Racional": "racional",
 "fil-caracteristicas|Arrazionala": "racional",
 "fil-caracteristicas|Crítica": "critica",
 "fil-caracteristicas|Kritika": "critica",
 "fil-caracteristicas|Universal": "universal",
 "fil-caracteristicas|Unibertsala": "universal",
 "fil-caracteristicas|Sistemática": "sistematica",
 "fil-caracteristicas|Sistematikoa": "sistematica",
 "fil-caracteristicas|Práctica": "practica",
 "fil-caracteristicas|Praktikoa": "practica",
 "fil-caracteristicas|Abierta": "abierta",
 "fil-caracteristicas|Irekia": "abierta",
 "fil-mente|Problema mente-cuerpo": "problema_mente_cuerpo",
 "fil-mente|Gogamen-gorputz arazoa": "problema_mente_cuerpo",
 "fil-mente|Monismo idealista": "monismo_idealista",
 "fil-mente|«Fantasma en la máquina»": "fantasma_maquina",
 "fil-mente|«Makinako mamua»": "fantasma_maquina",
 "fil-mente|Conductismo": "conductismo",
 "fil-mente|Konduktismoa": "conductismo",
 "fil-mente|Funcionalismo": "funcionalismo",
 "fil-mente|Funtzionalismoa": "funcionalismo",
 "fil-mente|Emergentismo": "emergentismo",
 "fil-mente|Emergentismoa": "emergentismo",
 "fil-concepciones|Cristianismo": "cristianismo_persona",
 "fil-concepciones|Kristautasuna": "cristianismo_persona",
 "fil-concepciones|Marx": "ser_social",
 "fil-concepciones|Animal simbólico (Cassirer)": "animal_simbolico",
 "fil-concepciones|Animalia sinbolikoa (Cassirer)": "animal_simbolico",
 "fil-verdad|Escepticismo": "escepticismo",
 "fil-verdad|Eszeptizismoa": "escepticismo",
 "fil-verdad|Relativismo": "relativismo",
 "fil-verdad|Erlatibismoa": "relativismo",
 "fil-verdad|Duda metódica (Descartes)": "duda_metodica",
 "fil-verdad|Zalantza metodikoa (Descartes)": "duda_metodica",
 "fil-verdad|Verdad pragmática": "verdad_pragmatica",
 "fil-verdad|Egia pragmatikoa": "verdad_pragmatica",
 "fil-verdad|Verdad como consenso": "verdad_consenso",
 "fil-verdad|Egia adostasun gisa": "verdad_consenso",
 "fil-verdad|Verdad y certeza": "verdad_y_certeza",
 "fil-verdad|Egia eta ziurtasuna": "verdad_y_certeza",
 "fil-metodo|Premisa": "premisa",
 "fil-metodo|前提": "premisa",
 "fil-metodo|Conclusión": "conclusion",
 "fil-metodo|Ondorioa": "conclusion",
 "fil-metodo|结论": "conclusion",
 "fil-metodo|Deducción": "deduccion",
 "fil-metodo|Dedukzioa": "deduccion",
 "fil-metodo|演绎": "deduccion",
 "fil-metodo|Inducción": "induccion",
 "fil-metodo|Indukzioa": "induccion",
 "fil-metodo|归纳": "induccion",
 "fil-ciencia|Inducción": "induccion",
 "fil-ciencia|Indukzioa": "induccion",
 "fil-ciencia|归纳": "induccion",
 "ipc-falacias|Generalización precipitada": "induccion",
 "ipc-falacias|Orokortze presakakoa": "induccion",
 "ipc-falacias|轻率概括": "induccion",
 "fil-metodo|Diálogo": "dialogo",
 "fil-metodo|Elkarrizketa": "dialogo",
 "fil-metodo|对话": "dialogo",
 "ipc-conceptos|Diálogo": "dialogo",
 "ipc-conceptos|Elkarrizketa": "dialogo",
 "ipc-conceptos|对话": "dialogo",
 "fil-metodo|Comentario de texto": "comentario_texto",
 "fil-metodo|Testu-iruzkina": "comentario_texto",
 "fil-saberes|Saber cotidiano": "saber_cotidiano",
 "fil-saberes|Eguneroko jakintza": "saber_cotidiano",
 "fil-saberes|Mito": "mito",
 "fil-saberes|Mitoa": "mito",
 "fil-saberes|迷思": "mito",
 "fil-saberes|Religión": "religion",
 "fil-saberes|Erlijioa": "religion",
 "fil-saberes|Arte": "arte_saber",
 "fil-saberes|Artea": "arte_saber",
 "fil-saberes|Técnica": "tecnica",
 "fil-saberes|Teknika": "tecnica",
 "fil-saberes|技巧": "tecnica",
 "fil-saberes|Teórico vs práctico": "teorico_practico",
 "fil-saberes|Teorikoa vs praktikoa": "teorico_practico",
 "fil-identidad|Conciencia": "conciencia",
 "fil-identidad|Kontzientzia": "conciencia",
 "fil-identidad|Lenguaje": "lenguaje",
 "fil-identidad|Hizkuntza": "lenguaje",
 "fil-identidad|Persona": "persona",
 "fil-identidad|Pertsona": "persona",
 "fil-identidad|Identidad como memoria (Locke)": "identidad_memoria",
 "fil-identidad|Identitatea oroimen gisa (Locke)": "identidad_memoria",
 "fil-identidad|Identidad narrativa": "identidad_narrativa",
 "fil-identidad|Identitate narratiboa": "identidad_narrativa",
 "fil-identidad|Sentido de la existencia": "sentido_existencia",
 "fil-identidad|Existentziaren zentzua": "sentido_existencia",
 "fil-identidad|Absurdo (Camus)": "absurdo",
 "fil-identidad|Absurdua (Camus)": "absurdo",
 "fil-ciencia|Método científico": "metodo_cientifico",
 "fil-ciencia|Metodo zientifikoa": "metodo_cientifico",
 "fil-ciencia|Ley científica": "ley_cientifica",
 "fil-ciencia|Lege zientifikoa": "ley_cientifica",
 "fil-ciencia|Teoría": "teoria",
 "fil-ciencia|Teoria": "teoria",
 "fil-ciencia|Paradigma (Kuhn)": "paradigma",
 "fil-ciencia|Pseudociencia": "pseudociencia",
 "fil-ciencia|Sasizientzia": "pseudociencia",
 "fil-ciencia|Ciencia y ética": "ciencia_y_etica",
 "fil-ciencia|Zientzia eta etika": "ciencia_y_etica",
 "fil-posverdad|Sesgo de confirmación": "sesgo_confirmacion",
 "fil-posverdad|Berrespen-alborapena": "sesgo_confirmacion",
 "fil-posverdad|确认偏见": "sesgo_confirmacion",
 "ipc-sesgos|Sesgo de confirmación": "sesgo_confirmacion",
 "ipc-sesgos|Berrespen-alborapena": "sesgo_confirmacion",
 "ipc-sesgos|确认偏见": "sesgo_confirmacion",
 "fil-posverdad|Clickbait": "clickbait",
 "fil-posverdad|Clickbait-a": "clickbait",
 "fil-posverdad|标题党": "clickbait",
 "ipc-publicidad|Clickbait": "clickbait",
 "ipc-publicidad|Clickbait-a": "clickbait",
 "ipc-publicidad|标题党": "clickbait",
 "fil-posverdad|Bots y desinformación": "bots",
 "fil-posverdad|Botak eta desinformazioa": "bots",
 "fil-posverdad|Verificación (fact-checking)": "verificacion",
 "fil-posverdad|Egiaztapena (fact-checking)": "verificacion",
 "ipc-publicidad|Contrastar fuentes": "verificacion",
 "ipc-publicidad|Iturriak alderatzea": "verificacion",
 "ipc-publicidad|对照多个来源": "verificacion",
 "fil-posverdad|Fuente fiable": "fuente_fiable",
 "fil-posverdad|Iturri fidagarria": "fuente_fiable",
 "fil-posverdad|Pensamiento crítico": "pensamiento_critico",
 "fil-posverdad|Pentsamendu kritikoa": "pensamiento_critico",
 "fil-posverdad|批判性思维": "pensamiento_critico",
 "ipc-conceptos|Pensamiento crítico": "pensamiento_critico",
 "ipc-conceptos|Pentsamendu kritikoa": "pensamiento_critico",
 "ipc-conceptos|批判性思维": "pensamiento_critico",
 "fil-posverdad|Antes de compartir": "antes_de_compartir",
 "fil-posverdad|Partekatu aurretik": "antes_de_compartir",
 "fil-etica|Ética y moral": "etica_y_moral",
 "fil-etica|Etika eta morala": "etica_y_moral",
 "fil-etica|Hedonismo": "hedonismo",
 "fil-etica|Hedonismoa": "hedonismo",
 "fil-etica|Emotivismo": "emotivismo",
 "fil-etica|Emotibismoa": "emotivismo",
 "fil-etica|Autonomía y heteronomía": "autonomia_heteronomia",
 "fil-etica|Autonomia eta heteronomia": "autonomia_heteronomia",
 "fil-arte|Belleza": "belleza",
 "fil-arte|Edertasuna": "belleza",
 "fil-arte|Objetivismo estético": "objetivismo_estetico",
 "fil-arte|Objektibismo estetikoa": "objetivismo_estetico",
 "fil-arte|Subjetivismo estético": "subjetivismo_estetico",
 "fil-arte|Subjektibismo estetikoa": "subjetivismo_estetico",
 "fil-arte|Juicio de gusto (Kant)": "juicio_de_gusto",
 "fil-arte|Gustu-judizioa (Kant)": "juicio_de_gusto",
 "fil-arte|Mímesis": "mimesis",
 "fil-arte|Mimesia": "mimesis",
 "fil-arte|Expresión": "expresion",
 "fil-arte|Adierazpena": "expresion",
 "fil-arte|Formalismo": "formalismo",
 "fil-arte|Formalismoa": "formalismo",
 "fil-arte|Teoría institucional": "teoria_institucional",
 "fil-arte|Teoria instituzionala": "teoria_institucional",
 "fil-arte|Funciones del arte": "funciones_arte",
 "fil-arte|Artearen funtzioak": "funciones_arte",
 "fil-logica|Negación (NOT)": "negacion",
 "fil-logica|Ezeztapena (NOT)": "negacion",
 "fil-logica|Conjunción (AND)": "conjuncion",
 "fil-logica|Konjuntzioa (AND)": "conjuncion",
 "fil-logica|Disyunción (OR)": "disyuncion",
 "fil-logica|Disjuntzioa (OR)": "disyuncion",
 "fil-logica|Condicional": "condicional",
 "fil-logica|Baldintzazkoa": "condicional",
 "fil-logica|Bicondicional": "bicondicional",
 "fil-logica|Bibaldintzazkoa": "bicondicional",
 "fil-logica|Tabla de verdad": "tabla_de_verdad",
 "fil-logica|Egia-taula": "tabla_de_verdad",
 "fil-logica|Argumento válido": "argumento_valido",
 "fil-logica|Argudio baliozkoa": "argumento_valido",
 "fil-logica|Álgebra de Boole": "algebra_de_boole",
 "fil-logica|Booleren aljebra": "algebra_de_boole",
 "fil-logica|Puertas lógicas": "puertas_logicas",
 "fil-logica|Ate logikoak": "puertas_logicas",
 "fil-politica|Formas de gobierno": "formas_de_gobierno",
 "fil-politica|Gobernu-formak": "formas_de_gobierno",
 "fil-politica|La democracia": "democracia",
 "fil-politica|Demokrazia": "democracia",
 "fil-politica|Derechos humanos": "derechos_humanos",
 "fil-politica|Giza eskubideak": "derechos_humanos",
 "fil-politica|人权": "derechos_humanos",
 "fil-presocraticos|Tales de Mileto": "tales",
 "fil-presocraticos|Tales Miletokoa": "tales",
 "presocraticos|Tales de Mileto": "tales",
 "presocraticos|Tales Miletokoa": "tales",
 "fil-presocraticos|Anaximandro": "anaximandro",
 "presocraticos|Anaximandro": "anaximandro",
 "fil-presocraticos|Anaxímenes": "anaximenes",
 "fil-presocraticos|Anaximenes": "anaximenes",
 "presocraticos|Anaxímenes": "anaximenes",
 "presocraticos|Anaximenes": "anaximenes",
 "fil-presocraticos|Pitágoras de Samos": "pitagoras",
 "fil-presocraticos|Pitagoras Samoskoa": "pitagoras",
 "presocraticos|Pitágoras": "pitagoras",
 "presocraticos|Pitagoras": "pitagoras",
 "fil-presocraticos|Parménides de Elea": "parmenides",
 "fil-presocraticos|Parmenides Eleakoa": "parmenides",
 "presocraticos|Parménides": "parmenides",
 "presocraticos|Parmenides": "parmenides",
 "fil-helenismo|La pregunta helenística": "pregunta_helenistica",
 "fil-helenismo|Galdera helenistikoa": "pregunta_helenistica",
 "fil-helenismo|Lo que depende de mí": "lo_que_depende_de_mi",
 "fil-helenismo|Nire esku dagoena": "lo_que_depende_de_mi",
 "ipc-conceptos|Opinión": "opinion",
 "ipc-conceptos|Iritzia": "opinion",
 "ipc-conceptos|观点": "opinion",
 "ipc-conceptos|Pregunta": "pregunta",
 "ipc-conceptos|Galdera": "pregunta",
 "ipc-conceptos|问题": "pregunta",
 "ipc-conceptos|Debate": "debate",
 "ipc-conceptos|Eztabaida": "debate",
 "ipc-conceptos|辩论": "debate",
 "ipc-conceptos|Criterio": "criterio",
 "ipc-conceptos|Irizpidea": "criterio",
 "ipc-conceptos|标准": "criterio",
 "ipc-conceptos|Conflicto": "conflicto",
 "ipc-conceptos|Gatazka": "conflicto",
 "ipc-conceptos|冲突": "conflicto",
 "ipc-conceptos|Negociación": "negociacion",
 "ipc-conceptos|Negoziazioa": "negociacion",
 "ipc-conceptos|协商": "negociacion",
 "ipc-falacias|Ad hominem": "ad_hominem",
 "ipc-falacias|人身攻击": "ad_hominem",
 "ipc-falacias|Falso dilema": "falso_dilema",
 "ipc-falacias|Dilema faltsua": "falso_dilema",
 "ipc-falacias|虚假两难": "falso_dilema",
 "ipc-falacias|Ad populum": "rebano",
 "ipc-falacias|诉诸多数": "rebano",
 "ipc-publicidad|Todos lo tienen (bandwagon)": "rebano",
 "ipc-publicidad|Denek dute (bandwagon)": "rebano",
 "ipc-publicidad|“人人都有”（从众）": "rebano",
 "ipc-sesgos|Arrastre (efecto bandwagon)": "rebano",
 "ipc-sesgos|Arrastatzea (bandwagon efektua)": "rebano",
 "ipc-sesgos|从众（乐队花车效应）": "rebano",
 "ipc-falacias|Apelación a la autoridad": "autoridad_falsa",
 "ipc-falacias|Autoritateari deia": "autoridad_falsa",
 "ipc-falacias|诉诸权威": "autoridad_falsa",
 "ipc-falacias|Falsa causa (post hoc)": "falsa_causa",
 "ipc-falacias|Kausa faltsua (post hoc)": "falsa_causa",
 "ipc-falacias|虚假因果（此后即因此）": "falsa_causa",
 "ipc-falacias|Apelación al miedo": "apelacion_miedo",
 "ipc-falacias|Beldurrari deia": "apelacion_miedo",
 "ipc-falacias|诉诸恐惧": "apelacion_miedo",
 "ipc-falacias|Apelación a la compasión": "apelacion_compasion",
 "ipc-falacias|Errukiari deia": "apelacion_compasion",
 "ipc-falacias|诉诸同情": "apelacion_compasion",
 "ipc-falacias|Apelación a la tradición": "apelacion_tradicion",
 "ipc-falacias|Tradizioari deia": "apelacion_tradicion",
 "ipc-falacias|诉诸传统": "apelacion_tradicion",
 "ipc-sesgos|Anclaje": "anclaje",
 "ipc-sesgos|Ainguraketa": "anclaje",
 "ipc-sesgos|锚定": "anclaje",
 "ipc-sesgos|Disponibilidad": "disponibilidad",
 "ipc-sesgos|Eskuragarritasuna": "disponibilidad",
 "ipc-sesgos|可得性": "disponibilidad",
 "ipc-sesgos|Efecto halo": "efecto_halo",
 "ipc-sesgos|Halo-efektua": "efecto_halo",
 "ipc-sesgos|光环效应": "efecto_halo",
 "ipc-sesgos|FOMO": "fomo",
 "ipc-sesgos|Sesgo ≠ falacia": "sesgo_vs_falacia",
 "ipc-sesgos|Alborapena ≠ faltsukeria": "sesgo_vs_falacia",
 "ipc-sesgos|偏见 ≠ 谬误": "sesgo_vs_falacia",
 "ipc-publicidad|Testimonio / influencer": "influencer",
 "ipc-publicidad|Testigantza / influencer-a": "influencer",
 "ipc-publicidad|代言 / 网红": "influencer",
 "ipc-moda|Influencers": "influencer",
 "ipc-moda|Influencerrak": "influencer",
 "ipc-moda|网红": "influencer",
 "ipc-publicidad|Escasez y urgencia": "escasez_urgencia",
 "ipc-publicidad|Urritasuna eta presa": "escasez_urgencia",
 "ipc-publicidad|稀缺与紧迫": "escasez_urgencia",
 "ipc-publicidad|Publicidad aspiracional": "publicidad_aspiracional",
 "ipc-publicidad|Publizitate aspirazionala": "publicidad_aspiracional",
 "ipc-publicidad|向往型广告": "publicidad_aspiracional",
 "ipc-publicidad|Humor y emoción": "humor_emocion",
 "ipc-publicidad|Umorea eta emozioa": "humor_emocion",
 "ipc-publicidad|幽默与情感": "humor_emocion",
 "ipc-publicidad|Alfabetización mediática": "alfabetizacion_mediatica",
 "ipc-publicidad|Alfabetatze mediatikoa": "alfabetizacion_mediatica",
 "ipc-publicidad|媒体素养": "alfabetizacion_mediatica",
 "ipc-huella|Huella ecológica": "huella_ecologica",
 "ipc-huella|Aztarna ekologikoa": "huella_ecologica",
 "ipc-huella|生态足迹": "huella_ecologica",
 "ipc-huella|Biocapacidad": "biocapacidad",
 "ipc-huella|Biogaitasuna": "biocapacidad",
 "ipc-huella|生物承载力": "biocapacidad",
 "ipc-huella|¿Cuántos planetas?": "cuantos_planetas",
 "ipc-huella|Zenbat planeta?": "cuantos_planetas",
 "ipc-huella|需要几个地球？": "cuantos_planetas",
 "ipc-huella|Día de la Sobrecapacidad": "dia_sobrecapacidad",
 "ipc-huella|Gaintasun Eguna": "dia_sobrecapacidad",
 "ipc-huella|地球超载日": "dia_sobrecapacidad",
 "ipc-huella|Huella de carbono": "huella_carbono",
 "ipc-huella|Karbono-aztarna": "huella_carbono",
 "ipc-huella|碳足迹": "huella_carbono",
 "ipc-huella|Justicia ambiental": "justicia_ambiental",
 "ipc-huella|Ingurumen-justizia": "justicia_ambiental",
 "ipc-huella|环境正义": "justicia_ambiental",
 "ipc-huella|Reducir, reutilizar, reciclar": "tres_erres",
 "ipc-huella|Murriztu, berrerabili, birziklatu": "tres_erres",
 "ipc-huella|减量、再利用、回收": "tres_erres",
 "ipc-huella|Greenwashing": "greenwashing",
 "ipc-huella|漂绿": "greenwashing",
 "ipc-prejuicios|¿Estereotipo o dato?": "estereotipo_o_dato",
 "ipc-prejuicios|Estereotipoa ala datua?": "estereotipo_o_dato",
 "ipc-prejuicios|是刻板印象还是数据？": "estereotipo_o_dato",
 "ipc-prejuicios|Racismo": "racismo",
 "ipc-prejuicios|Arrazakeria": "racismo",
 "ipc-prejuicios|种族主义": "racismo",
 "ipc-prejuicios|Xenofobia": "xenofobia",
 "ipc-prejuicios|仇外": "xenofobia",
 "ipc-prejuicios|Aporofobia": "aporofobia",
 "ipc-prejuicios|恐贫症": "aporofobia",
 "ipc-prejuicios|Machismo y sexismo": "machismo",
 "ipc-prejuicios|Matxismoa eta sexismoa": "machismo",
 "ipc-prejuicios|大男子主义与性别歧视": "machismo",
 "ipc-prejuicios|LGTBIfobia": "lgtbifobia",
 "ipc-prejuicios|恐同恐跨（LGTBI恐惧）": "lgtbifobia",
 "ipc-prejuicios|Edadismo": "edadismo",
 "ipc-prejuicios|Adinakeria": "edadismo",
 "ipc-prejuicios|年龄歧视": "edadismo",
 "ipc-prejuicios|Capacitismo": "capacitismo",
 "ipc-prejuicios|Gaitasunkeria": "capacitismo",
 "ipc-prejuicios|对残障者的歧视": "capacitismo",
 "ipc-prejuicios|Prejuicio religioso": "prejuicio_religioso",
 "ipc-prejuicios|Aurreiritzi erlijiosoa": "prejuicio_religioso",
 "ipc-prejuicios|宗教偏见": "prejuicio_religioso",
 "ipc-prejuicios|Por la apariencia": "por_la_apariencia",
 "ipc-prejuicios|Itxuragatik": "por_la_apariencia",
 "ipc-prejuicios|以貌取人": "por_la_apariencia",
 "ipc-prejuicios|Estigma de la salud mental": "estigma_salud_mental",
 "ipc-prejuicios|Osasun mentalaren estigma": "estigma_salud_mental",
 "ipc-prejuicios|对心理健康的污名": "estigma_salud_mental",
 "ipc-prejuicios|¿Qué puedo hacer?": "que_puedo_hacer",
 "ipc-prejuicios|Zer egin dezaket?": "que_puedo_hacer",
 "ipc-prejuicios|我能做什么？": "que_puedo_hacer",
 "ipc-moda|52 colecciones al año": "colecciones_semanales",
 "ipc-moda|52 bilduma urtean": "colecciones_semanales",
 "ipc-moda|每年52个系列": "colecciones_semanales",
 "ipc-moda|120.000 millones": "millones_de_prendas",
 "ipc-moda|120.000 milioi": "millones_de_prendas",
 "ipc-moda|1200亿件": "millones_de_prendas",
 "ipc-moda|Sin estrenar": "sin_estrenar",
 "ipc-moda|Estreinatu gabe": "sin_estrenar",
 "ipc-moda|从未穿过": "sin_estrenar",
 "ipc-moda|El top de fiesta": "top_de_fiesta",
 "ipc-moda|Festarako topa": "top_de_fiesta",
 "ipc-moda|派对上衣": "top_de_fiesta",
 "ipc-moda|Ropa de petróleo": "ropa_de_petroleo",
 "ipc-moda|Petroliozko arropa": "ropa_de_petroleo",
 "ipc-moda|石油做的衣服": "ropa_de_petroleo",
 "ipc-moda|El mito del reciclaje": "mito_reciclaje",
 "ipc-moda|Birziklapenaren mitoa": "mito_reciclaje",
 "ipc-moda|回收的神话": "mito_reciclaje",
 "ipc-moda|El destino: Bulgaria": "destino_bulgaria",
 "ipc-moda|Helmuga: Bulgaria": "destino_bulgaria",
 "ipc-moda|最终去向：保加利亚": "destino_bulgaria",
 "ipc-moda|Humo tóxico": "humo_toxico",
 "ipc-moda|Ke toxikoa": "humo_toxico",
 "ipc-moda|有毒烟雾": "humo_toxico",
 "ipc-moda|Felicidad de un día": "felicidad_de_un_dia",
 "ipc-moda|Egun bateko zoriona": "felicidad_de_un_dia",
 "ipc-moda|一天的快乐": "felicidad_de_un_dia",
 "ipc-moda|Alternativas": "alternativas_moda",
 "ipc-moda|Alternatibak": "alternativas_moda",
 "ipc-moda|替代办法": "alternativas_moda",
 "ipc-moda|La prenda más sostenible": "prenda_sostenible",
 "ipc-moda|Jantzirik jasangarriena": "prenda_sostenible",
 "ipc-moda|最可持续的衣服": "prenda_sostenible"
};
